### ISSUE TITLE
Testing - Write test cases & code for Feature 1 (Login & Account Creation)

### ISSUE THREAD

**Issue by harshini53** [LWJ-Nicholas/DevOps_Oct2023_TeamC_Assignment#25]

**Comment by LWJ-Nicholas** [comment]
- Try to retrieve data from database to see if its successful
- Try to add record to database and check is the record is added (Valid/Invalid)
- Test the functions in the backend created for login (check for response)
- Test the functions in the backend created for create account (check for response)
